# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

set_executor <- function(ptr) {
    .Call('_BiocSingular_set_executor', PACKAGE = 'BiocSingular', ptr)
}

compute_scale <- function(mat, centers, nthreads) {
    .Call('_BiocSingular_compute_scale', PACKAGE = 'BiocSingular', mat, centers, nthreads)
}

